run:
  timeout: 10m
  skip-files:
    - ".*\\.pb\\.go$"

  modules-download-mode: vendor

  build-tags:
    - dfrunsecurity
    - dfaddgit
    - dfaddchecksum

linters:
  enable:
    - depguard
    - gofmt
    - goimports
    - gosimple
    - revive
    - govet
    - importas
    - ineffassign
    - misspell
    - staticcheck
    - typecheck
    - unused
    - bodyclose
    - errname
    - makezero
    - whitespace
    - nolintlint
    - gosec
    - forbidigo
  disable-all: true

linters-settings:
  depguard:
    rules:
      main:
        deny:
          - pkg: "io/ioutil"
            desc: io/ioutil has been deprecated, see https://go.dev/doc/go1.16#ioutil
  forbidigo:
    forbid:
      - p: ^fmt\.Errorf$
        msg: use errors.Errorf instead
      - p: ^logrus\.(Trace|Debug|Info|Warn|Warning|Error|Fatal)(f|ln)?$
        msg: use bklog.G(ctx) instead of logrus directly'
      - p: ^context\.WithCancel$
        msg: use context.WithCancelCause with cancel(errors.WithStack(context.Canceled)) instead'
      - p: ^context\.WithTimeout$
        msg: use context.WithTimeoutCause(..., errors.WithStack(context.DeadlineExceeded)) instead'
      - p: ^context\.WithDeadline$
        msg: use context.WithDeadlineCause(..., errors.WithStack(context.DeadlineExceeded)) instead'
      - p: ^context\.Context\.Err$
        msg: use context.Cause(ctx) instead'
    analyze-types: true
  importas:
    alias:
      - pkg: "github.com/opencontainers/image-spec/specs-go/v1"
        alias: "ocispecs"
      - pkg: "github.com/opencontainers/go-digest"
        alias: "digest"
    no-unaliased: true
  gosec:
    excludes:
      - G101  # Potential hardcoded credentials (false positives)
      - G402  # TLS MinVersion too low
      - G601  # Implicit memory aliasing in for loop (false positives)
      - G504  # Import blocklist: net/http/cgi
    config:
      G306: "0644"

issues:
  exclude-rules:
    - linters:
        - revive
      text: "stutters"
    - linters:
        - revive
      text: "empty-block"
    - linters:
        - revive
      text: "superfluous-else"
    - linters:
        - revive
      text: "unused-parameter"
    - linters:
        - revive
      text: "redefines-builtin-id"
    - linters:
        - revive
      text: "if-return"
